# Generated by Django 4.1.6 on 2023-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('sauce', models.CharField(max_length=255)),
                ('drink', models.CharField(max_length=255)),
                ('toppings', models.ManyToManyField(related_name='pizzas', to='Home.pizzatopping')),
            ],
        ),
    ]
