# Generated by Django 4.1.6 on 2023-02-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_cheese'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cheese',
            new_name='Cheeses',
        ),
    ]
