# Generated by Django 4.1.6 on 2023-02-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_cheese_cheeses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cheeses',
            new_name='Cheese',
        ),
    ]
