# Generated by Django 4.1.6 on 2023-02-23 17:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('additional_toppings', models.ManyToManyField(blank=True, related_name='additional_toppings', to='Home.pizzatopping')),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.cheese')),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.pizzacrust')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.order')),
            ],
        ),
        migrations.AddField(
            model_name='pizzasauce',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.pizzasauce'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_topping', to='Home.pizzatopping'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.pizzasize'),
        ),
    ]
