# Generated by Django 4.1.6 on 2023-02-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_order_country_alter_order_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='cheese',
            field=models.ForeignKey(default='Mozzarella', on_delete=django.db.models.deletion.CASCADE, to='Home.cheese'),
        ),
        migrations.AlterField(
            model_name='order',
            name='crust',
            field=models.ForeignKey(default='Regular', on_delete=django.db.models.deletion.CASCADE, to='Home.pizzacrust'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sauce',
            field=models.ForeignKey(default='Tomato', on_delete=django.db.models.deletion.CASCADE, to='Home.pizzasauce'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(default='Small', on_delete=django.db.models.deletion.CASCADE, to='Home.pizzasize'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(default='', max_length=20),
        ),
    ]
